dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

services:
  - docker

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run build -- --prod

after_success:
  - docker build -t esuau/lifeline .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
